# Generated by Django 5.2.15 on 2026-06-11 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "icono",
                    models.CharField(
                        default="bi-box",
                        help_text="Ejemplo: bi-laptop, bi-phone, bi-headphones",
                        max_length=50,
                        verbose_name="Ícono Bootstrap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sesion_id",
                    models.CharField(max_length=100, verbose_name="ID de sesión"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("usuario", "Usuario"), ("bot", "Bot")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="MensajeBuzon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                ("leido", models.BooleanField(default=False, verbose_name="¿Leído?")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_buzon",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Buzón",
                "verbose_name_plural": "Mensajes de Buzón",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del producto"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio ($)"
                    ),
                ),
                (
                    "precio_oferta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio en oferta ($)",
                    ),
                ),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True,
                        help_text="Pega aquí la URL de una imagen del producto",
                        verbose_name="URL de imagen",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Unidades disponibles"
                    ),
                ),
                (
                    "es_oferta",
                    models.BooleanField(default=False, verbose_name="¿Está en oferta?"),
                ),
                (
                    "destacado",
                    models.BooleanField(
                        default=False, verbose_name="¿Producto destacado?"
                    ),
                ),
                (
                    "fecha_agregado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="tienda.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-fecha_agregado"],
            },
        ),
    ]
